name: fumiko
description: Fumiko est un « Simple Text based MMORPG », c’est-à-dire un RPG basé sur du
  texte, avec une simple jouabilité, en d’autres termes Fumiko offre
  l’expérience RPG simple tout en vous permettant de jouer avec des milliers de
  joueurs dans un univers Japonais. ⛩️
repository: https://github.com/kanekireal/Fumiko
version: 1.0.0
publish_to: "none"


environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  connectivity_plus: ^4.0.2
  firebase_analytics: ^10.4.5
  firebase_app_check: ^0.1.5+2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  firebase_performance: ^0.9.2+5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.2
  intl: ^0.18.1
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^4.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/graphics/
    - assets/sounds/
  fonts:
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-Bold.ttf
        - asset: fonts/Dosis-ExtraBold.ttf
        - asset: fonts/Dosis-ExtraLight.ttf
        - asset: fonts/Dosis-Light.ttf
        - asset: fonts/Dosis-Medium.ttf
        - asset: fonts/Dosis-Regular.ttf
        - asset: fonts/Dosis-SemiBold.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: fr_FR
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n